"""Safety helpers for local MCP file and row-count operations."""

from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path

from great_generator.mcp.config import MCPConfig, load_config

SYNTHETIC_DATA_NOTICE = (
    "This data is synthetic. It was generated by Great Generator. It is not production "
    "data, and it is not an anonymized, masked, or de-identified copy of production records."
)
SUPPORTED_FORMATS = {"csv", "jsonl", "parquet"}
_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")


class GreatGeneratorMCPError(ValueError):
    """Raised when an MCP tool request is unsafe or invalid."""


def active_config(config: MCPConfig | None = None) -> MCPConfig:
    return config or load_config()


def validate_format(value: str) -> str:
    normalized = str(value or "").strip().lower()
    if normalized not in SUPPORTED_FORMATS:
        supported = ", ".join(sorted(SUPPORTED_FORMATS))
        raise GreatGeneratorMCPError(f"Unsupported format '{value}'. Use one of: {supported}.")
    return normalized


def validate_preview_rows(preview_rows: int | None, config: MCPConfig | None = None) -> int:
    cfg = active_config(config)
    value = cfg.default_preview_rows if preview_rows is None else int(preview_rows)
    if value < 0:
        raise GreatGeneratorMCPError("preview_rows must be zero or greater.")
    return min(value, cfg.max_preview_rows)


def validate_row_count(
    rows: int,
    *,
    allow_large: bool = False,
    config: MCPConfig | None = None,
    label: str = "rows",
) -> int:
    cfg = active_config(config)
    value = int(rows)
    if value <= 0:
        raise GreatGeneratorMCPError(f"{label} must be greater than zero.")
    if value > cfg.hard_max_rows:
        raise GreatGeneratorMCPError(
            f"{label}={value} exceeds the hard MCP row limit of {cfg.hard_max_rows}. "
            "Lower the row count or change GREAT_GENERATOR_MCP_HARD_MAX_ROWS."
        )
    if value > cfg.max_rows and not allow_large:
        raise GreatGeneratorMCPError(
            f"{label}={value} exceeds the MCP row limit of {cfg.max_rows}. "
            "Lower the row count or set allow_large=True for this request."
        )
    return value


def validate_row_mapping(
    rows: Mapping[str, int] | int | None,
    *,
    allow_large: bool = False,
    config: MCPConfig | None = None,
) -> dict[str, int] | int | None:
    if rows is None:
        return None
    if isinstance(rows, Mapping):
        validated = {
            str(table): validate_row_count(
                int(count),
                allow_large=allow_large,
                config=config,
                label=f"rows[{table}]",
            )
            for table, count in rows.items()
        }
        total = sum(validated.values())
        validate_row_count(total, allow_large=allow_large, config=config, label="total rows")
        return validated
    return validate_row_count(int(rows), allow_large=allow_large, config=config)


def resolve_output_dir(output_dir: str | Path | None, config: MCPConfig | None = None) -> Path:
    if output_dir is None or str(output_dir).strip() == "":
        raise GreatGeneratorMCPError("output_dir is required for MCP generation tools.")
    cfg = active_config(config)
    path = _resolve_under_root(output_dir, cfg)
    ensure_within_root(path, cfg, label="output_dir")
    path.mkdir(parents=True, exist_ok=True)
    return path


def resolve_input_path(input_path: str | Path, config: MCPConfig | None = None) -> Path:
    if input_path is None or str(input_path).strip() == "":
        raise GreatGeneratorMCPError("input_path is required.")
    cfg = active_config(config)
    path = _resolve_under_root(input_path, cfg)
    ensure_within_root(path, cfg, label="input_path")
    if not path.exists():
        raise GreatGeneratorMCPError(f"Input path does not exist: {path}.")
    return path


def output_file_path(
    output_dir: Path,
    name: str,
    format_name: str,
    *,
    overwrite: bool = False,
) -> Path:
    stem = safe_file_stem(name)
    suffix = ".jsonl" if format_name == "jsonl" else f".{format_name}"
    path = output_dir / f"{stem}{suffix}"
    ensure_can_write(path, overwrite=overwrite)
    return path


def ensure_can_write(path: Path, *, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise GreatGeneratorMCPError(
            f"Output file already exists: {path}. Pass overwrite=True to replace it."
        )


def safe_file_stem(value: str) -> str:
    raw = str(value or "").strip()
    if not raw:
        raise GreatGeneratorMCPError("File name cannot be empty.")
    if any(separator in raw for separator in ("/", "\\")) or raw in {".", ".."}:
        raise GreatGeneratorMCPError(f"Unsafe file name: {value!r}.")
    cleaned = _SAFE_NAME_RE.sub("_", raw).strip("._-")
    if not cleaned:
        raise GreatGeneratorMCPError(f"Unsafe file name: {value!r}.")
    return cleaned[:120]


def ensure_within_root(path: Path, config: MCPConfig, *, label: str) -> None:
    try:
        path.resolve().relative_to(config.allowed_root.resolve())
    except ValueError as exc:
        raise GreatGeneratorMCPError(
            f"{label} must stay under allowed root {config.allowed_root}. Got {path.resolve()}."
        ) from exc


def _resolve_under_root(path: str | Path, config: MCPConfig) -> Path:
    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = config.allowed_root / candidate
    return candidate.resolve()
